import "../modules/cart";
import "../modules/infoBlock";
import "../modules/localstorage";
import "../modules/main";
import "../modules/modal";
import "../modules/productBlock";
import "../modules/renderProducts";
import "../modules/tabs";
import "../modules/timer";
